BCLA_site/urls.py
from django.contrib import admin
from django.urls import include, path
import network.views as network_views

urlpatterns = [
    path('', network_views.home_page, name='home_page'),
    path('admin/', admin.site.urls),
    path('all/', network_views.return_all_node, name='all_node'),
    path('node/', include('network.urls')),
    path('description/', network_views.return_node_description, name='node_description'),
    path('download/', network_views.download_file, name='download_file')
]

network/urls.py
from django.contrib import admin
from django.urls import include, path
from network.views import home_page, return_node_page, return_all_node, return_node_description

urlpatterns = [
    path('<str:node_name>', return_node_page, name="return_node_page")
]

network/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class NetworkNode(models.Model):
    node_name = models.CharField(max_length=15)
    node_description = models.TextField()

    def __str__(self):
        return self.node_name


class NetworkEdge(models.Model):
    Source = models.TextField()
    Target = models.TextField()
    Weight = models.IntegerField()

    def __str__(self):
        return self.Source + "->" + self.Target


class BNetworkEdge(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    source = models.IntegerField()
    target = models.IntegerField()
    edge_type = models.IntegerField()
    database = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'b_network_edge'


class BNetworkNode(models.Model):

    CONTROL_TYPE = (
        (0, 'control_hub'),
        (1, 'head'),
        (2, 'tail'),
        (3, 'head/tail')
    )
    id = models.AutoField(unique=True, primary_key=True)
    name = models.CharField(max_length=50)
    indegree = models.IntegerField(blank=True, null=True)
    outdegree = models.IntegerField(blank=True, null=True)
    degree = models.IntegerField(blank=True, null=True)
    control_type = models.IntegerField(choices=CONTROL_TYPE)
    is_sensitive = models.IntegerField()
    control_type_pnas = models.IntegerField()
    is_essential_gene = models.IntegerField()
    is_evolutionary_mouse = models.IntegerField()
    is_evolutionary_fish = models.IntegerField()
    is_evolutionary_fly = models.IntegerField()
    is_evolutionary_worm = models.IntegerField()
    is_evolutionary_yeast = models.IntegerField()
    is_cell_signaling_signaling_protein = models.IntegerField()
    is_cell_signaling_membrane_receptors = models.IntegerField()
    is_cell_signaling_kinases = models.IntegerField()
    is_cell_signaling_transcription_factors = models.IntegerField()
    is_protein_abundance_high_copy_number = models.IntegerField()
    is_protein_abundance_moderate_copy_number = models.IntegerField()
    is_protein_adundance_low_copy_number = models.IntegerField()
    is_protein_adundance_very_low_copy_number = models.IntegerField()
    is_post_translational_modification_acetylation = models.IntegerField()
    is_post_translational_modification_phosphorylation_ps_pt = models.IntegerField()
    is_post_transaltional_modification_phosphorylation_py = models.IntegerField()
    is_post_translational_modification_ubiquitination = models.IntegerField()
    is_disease_genes_cancer_driver = models.IntegerField()
    is_disease_genes_cancer1 = models.IntegerField()
    is_disease_genes_omim = models.IntegerField()
    is_virus_targets_hiv_rnai = models.IntegerField(null=True)
    is_virus_targets_hiv_ppi = models.IntegerField(null=True)
    is_virus_targets_all_viruses = models.IntegerField(null=True)
    is_drug_target_therapeutic_targets = models.IntegerField()
    is_drug_target_fda_approved = models.IntegerField()
    is_drug_target_druggable = models.IntegerField()
    is_regulators_of_cell_proliferation_go_genes = models.IntegerField()
    is_regulatior_of_cell_proliferation_stop_genes = models.IntegerField()
    is_immune_genes_core_ctl_genes = models.IntegerField()
    is_immune_genes_car_genes = models.IntegerField()
    is_immune_genes_checkpoint_genes = models.IntegerField()
    description = models.CharField(max_length=1000, null=True)

    class Meta:
        managed = True
        db_table = 'b_network_node'

network/views.py
import json
import os
import mimetypes

from django.shortcuts import render_to_response, render, redirect, reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.contrib import messages
from django.http.response import HttpResponse

import pandas as pd

from .models import *

import network.dao as network_dao
import network.tools as network_tools


# Create your views here.
@csrf_exempt
def home_page(request):
    # 搜索后
    if request.method == 'POST':
        context = {}
        searched = request.POST['searched']
        # # 这里后改为自己写的函数，用来获取基因信息
        # df_edge = network_dao.read_gene_edge()
        # df_node = network_dao.read_gene_node()
        # node_descriptions = df_node[df_node.Gene == searched]
        # # node_descriptions = list(node_descriptions)
        # json_records = df_node.reset_index().to_json(orient='records')
        # arr = json.loads(json_records)
        # table = {'d': arr}
        # neighbor_nodes = network_dao.get_neighbor_node(searched, df_edge)
        # neighbor_nodes = df_node.query("Gene == @neighbor_nodes")
        # G = network_tools.convert_to_G(df_edge)
        # G = network_tools.ego_graph(G, searched)
        # script, div = network_tools.draw_the_network(G)
        # context["searched"] = searched
        # context["script"] = script
        # context["div"] = div

        try:
            # 获取被搜索基因的信息
            gene_info = network_dao.get_node_by_name(searched)
            # 获取被搜索基因邻居节点的信息
            neigbor_info = network_dao.get_neighbor_by_node_id(gene_info.id)
            neigbor_info = pd.DataFrame(neigbor_info)
            # 获取自我中心网
            G = network_tools.convert_to_G(network_dao.get_all_edge())
            G = network_tools.ego_graph(G, gene_info.id)
            script, div = network_tools.draw_the_network(G)
            ego_graph = {'script': script, 'div': div}

            context["gene_info"] = gene_info
            context["neigbor_info"] = neigbor_info
            context["ego_graph"] = ego_graph

            return render_to_response('main.html', context)
        except:
            return render_to_response('main.html', {'searched': searched})

    # 未搜索
    else:
        return render_to_response('main.html')


# 返回
def return_all_node(request):
    df = network_dao.read_edge_data()
    G = network_tools.convert_to_G(df)
    network_tools.draw_the_network(G)
    return render_to_response('network.html')


# 此函数是用来返回节点自我中心网的可视化页面，后续须做到description页面里去
def return_node_page(request, node_name):
    df = network_dao.read_edge_data()
    G = network_tools.convert_to_G(df)
    G = network_tools.ego_graph(G, node_name)
    network_tools.draw_the_network(G)
    return render_to_response('network.html')


@csrf_exempt
def return_node_description(request):
    if request.method == 'POST':
        searched = request.POST['searched']

        # 这里后改为自己写的函数，用来获取基因信息
        df_edge = network_dao.read_gene_edge()
        df_node = network_dao.read_gene_node()
        node_descriptions = df_node[df_node.Gene == searched]
        # node_descriptions = list(node_descriptions)
        json_records = df_node.reset_index().to_json(orient='records')
        arr = json.loads(json_records)
        context = {'d': arr}
        neighbor_nodes = network_dao.get_neighbor_node(searched, df_edge)
        neighbor_nodes = df_node.query("Gene == @neighbor_nodes")
        G = network_tools.convert_to_G(df_edge)
        try:
            G = network_tools.ego_graph(G, searched)
            script, div = network_tools.draw_the_network(G)
            return render_to_response('description_page.html', {'searched': searched,
                                                                'node_descriptions': node_descriptions,
                                                                'neighbor_nodes': neighbor_nodes,
                                                                'script': script,
                                                                'div': div,
                                                                'd': context})

        except:
            return redirect('home_page')

    else:
        return render_to_response('description_page.html')


def download_file(request):
    filename = 'new.csv'
    filepath = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = open(filepath, 'r')
    mime_type, _ = mimetypes.guess_type(filepath)
    response = HttpResponse(path, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response

network/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=ABeeZee">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>{% block title %}{% endblock %}</title>


    {% block bokeh_css %}{% endblock %}
    {% block description_css %}{% endblock %}

    <style type="text/css">
        * {
            margin: 0;
            padding: 0;
        }

        p {
            display: block;
            margin-block-start: 1em;
            margin-block-end: 1em;
            margin-inline-start: 0px;
            margin-inline-end: 0px;
        }

        div.nav {
            background-color: #eee;
            border-bottom: 1px solid #ccc;
            padding: 10px;
        }

        div.nav a {
            text-decoration: none;
            color: #000;
            padding: 5px 10px;
        }

        div.nav a.logo {
            display: inline-block;
            font-size: 120%;
        }
    </style>
</head>

<body>
<div class="nav">
    <a class="logo" href="{% url 'home_page' %}">
        <h3>Cancer Keeping Gene</h3>
    </a>
</div>
<hr>
{% block content %}{% endblock %}
</body>

{% block bokeh_js %}{% endblock %}
</html>

network/templates/description_page.html
{% extends 'base.html' %}

{% block title %}
    Gene Description
{% endblock %}

{% block bokeh_css %}
    <link href=”http://cdn.pydata.org/bokeh/release/bokeh-2.3.3.min.css" rel=”stylesheet” type=”text/css”>
    <link href=”http://cdn.pydata.org/bokeh/release/bokeh-widgets-2.3.3.min.css" rel=”stylesheet” type=”text/css”>
{% endblock %}

{% block content %}
    <div>
        <div>
            <div class="container">
                {{ div| safe }}
            </div>
            <h1>Description</h1>
            <br>
            <div>
                <table class="table">
                    <tr>
                        {% for col in node_descriptions.columns %}
                            <td>
                                {{ col }}
                            </td>
                        {% endfor %}
                    </tr>
                    {% for index, row in node_descriptions.iterrows %}
                        <tr>
                            {% for cell in row %}
                                <td>
                                    {{ cell }}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
            </p>
{#            <div class="container">#}
{#                <table class="table">#}
{#                    <thread>#}
{#                        <tr>#}
{#                            <th>Gene</th>#}
{#                            <th>Indegree</th>#}
{#                            <th>Outdegree</th>#}
{#                            <th>Degree</th>#}
{#                            <th>Node Type</th>#}
{#                            <th>Node Class(PPI)</th>#}
{#                            <th>Essential gene</th>#}
{#                            <th>Mouse</th>#}
{#                            <th>Fish</th>#}
{#                            <th>Fly</th>#}
{#                            <th>Worm</th>#}
{#                            <th>Yeast</th>#}
{#                            <th>Signaling proteins</th>#}
{#                            <th>Membrane Receptors</th>#}
{#                            <th>Kinases</th>#}
{#                            <th>Transcription Factors</th>#}
{#                            <th>High Copy Number</th>#}
{#                            <th>Moderate Copy Number</th>#}
{#                            <th>Low Copy Number</th>#}
{#                            <th>Very Low Copy Number</th>#}
{#                            <th>Acetylation</th>#}
{#                            <th>Phosphorylation (pS/pT)</th>#}
{#                            <th>Phosphorylation (pY)</th>#}
{#                            <th>Ubiquitination</th>#}
{#                            <th>Cancer driver genes</th>#}
{#                            <th>Cancer I</th>#}
{#                            <th>OMIM</th>#}
{#                            <th>HIV (RNAi)</th>#}
{#                            <th>HIV (PPI)</th>#}
{#                            <th>All Viruses</th>#}
{#                            <th>Therapeutic</th>#}
{#                            <th>FDA approved</th>#}
{#                            <th>Druggable</th>#}
{#                            <th>GO Genes</th>#}
{#                            <th>STOP Genes</th>#}
{#                            <th>coreCTL_genes</th>#}
{#                            <th>CAR_genes</th>#}
{#                            <th>checkpoint_genes</th>#}
{#                        </tr>#}
{#                    </thread>#}
{#                    <tbody>#}
{#                    {% if d %}#}
{#                        {% for i in d %}#}
{#                            <tr>#}
{#                                <td>{{ i.Gene }}</td>#}
{#                                <td>{{ i.Indegree }}</td>#}
{#                                <td>{{ i.Outdegree }}</td>#}
{#                                <td>{{ i.NodeType }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                                <td>{{ i }}</td>#}
{#                            </tr>#}
{#                        {% endfor %}#}
{#                    {% endif %}#}
{#                    </tbody>#}
{#                </table>#}
{#            </div>#}
        </div>


        <div>
            <h1>Neighbor Node</h1>
            <div>
                <table class="table">
                    <tr>
                        {% for col in neighbor_nodes.columns %}
                            <td>
                                {{ col }}
                            </td>
                        {% endfor %}
                    </tr>
                    {% for index, row in neighbor_nodes.iterrows %}
                        <tr>
                            {% for cell in row %}
                                <td>
                                    {{ cell }}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div>
            <h1>Network Analysis</h1>
        </div>

    </div>

{% endblock %}

{% block bokeh_js %}
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.3.3.min.js"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.3.3.min.js"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.3.3.min.js"></script>
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.3.3.min.js"></script>
    {{ script| safe }}
    <script src="https://lib.baomitu.com/jquery/3.6.0/jquery.min.js"></script>

{% endblock %}

network/templates/home_page.html
{% extends 'base.html' %}

{# 页面标题 #}
{% block title %}
    Cancer Keeping Gene
{% endblock %}

{# 页面内容 #}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <form class="input-group" method="post" action="{% url 'node_description' %}">
                            {% csrf_token %}
                            <input type="text" class="form-control input-lg" placeholder="Input Gene Name"
                                   name="searched" />
                            <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="submit" style="background-color: #000 !important;border-color: #000">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <a href="{% url 'all_node' %}">
        <p>Show the all</p>
    </a>
{% endblock %}

network/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Cancer Keeping Gene</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- 这里加载bokeh的css组件 -->
    <link href=”http://cdn.pydata.org/bokeh/release/bokeh-2.3.3.min.css" rel=”stylesheet” type=”text/css”>
    <link href=”http://cdn.pydata.org/bokeh/release/bokeh-widgets-2.3.3.min.css" rel=”stylesheet” type=”text/css”>

</head>
<body>

<div class="class container">
    <!--这里是网站大标题部分-->
    <div class="jumbotron col-md-10 col-md-push-1">
        <div class="row">
            <div class="col-xs-12 col-sm-10">
                <h1>
                    <a href="{% url 'home_page' %}">Cancer Keeping Gene</a>
                </h1>
{#                <p>#}
{#                    这里可以加一些注释 <a>这里是一个超链接</a>.#}
{#                </p>#}
            </div>

        </div>
    </div>

    <!--这里是搜索框部分-->
    <div class="col-md-10 col-md-push-1" id="search">
        <form method="post" id="gene-search-form">
            {% csrf_token %}
            <div class="input-group">
                <input type="text" id="gene-search-query-text" class="form-control input-lg"
                       placeholder="Input The Gene Name..." name="searched">
                <span class="input-group-addon">
              <button type="submit" class="no-style">
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
              </button>
            </span>
            </div>
        </form>
    </div>

    {% if searched %}
        <!-- 这里放搜索错误信息 -->
        <div class="col-md-4 col-md-push-1">
            <p>There is no Gene named "{{ searched }}"</p>
        </div>
    {% endif %}

    {% if gene_info %}
        <!--如果未搜索，隐藏下面的内容-->
        <div class="col-md-10 col-md-push-1" id="hide">
            <!--这里是搜索框下方导航栏部分-->
            <div class="navigationbar">
                <ul class="breadcrumb">
                    <li class="navdes"><a href="#">Description</a></li>
                    <li class="navnei"><a href="#">Neighbor Info</a></li>
                </ul>
            </div>

            <div class="description">
                <!-- 这里放自我中心网图 -->
                <div class="col-md-7">
                    {{ ego_graph.div| safe }}
                </div>

                <!--这里放基因的详情信息-->
                <div id="gene-description">
                    <div class="col-md-4 col-md-push-1">
                        <h3>Gene Name: {{ gene_info.name }}</h3>
                        <h3>Degree: {{ gene_info.degree }}</h3>
                        <h3>Node Type: {{ gene_info.get_control_type_display }}</h3>
                    </div>
                </div>
            </div>

            <div class="neighbor">
                <!--这里放邻居节点的列表-->
                <div class="col-md-12" style="overflow-x: scroll;" id="neighbor-node">
                    <table class="table">
                        <tr>
                            {% for col in neigbor_info.columns %}
                                <td>
                                    {{ col }}
                                </td>
                            {% endfor %}
                        </tr>
                        {% for index, row in neigbor_info.iterrows %}
                            <tr>
                                {% for cell in row %}
                                    <td>
                                        {{ cell }}
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>


            <!--这里放自我中心网统计信息-->
            <div id="ego-graph"></div>
        </div>
    {% endif %}

</div>


</body>

<script>
    var navdes = document.querySelector('.navdes');
    var navnei = document.querySelector('.navnei');
    var description = document.querySelector('.description');
    var neighbor = document.querySelector('.neighbor');

    {#description.style.display = 'none';#}
    neighbor.style.display = 'none';
    navdes.onclick = function () {
        description.style.display = 'inline';
        neighbor.style.display = 'none';
    }
    navnei.onclick = function () {
        description.style.display = 'none';
        neighbor.style.display = 'inline';
    }


</script>


<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"
        integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ"
        crossorigin="anonymous"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
        integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd"
        crossorigin="anonymous"></script>
<!--这里加载bokeh所需要的库-->
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.3.3.min.js"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.3.3.min.js"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-2.3.3.min.js"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-api-2.3.3.min.js"></script>
{{ ego_graph.script| safe }}
<script src="https://lib.baomitu.com/jquery/3.6.0/jquery.min.js"></script>
</html>